import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  let userName: string = 'Wicleice ';
  let hasLoggedIn: boolean = true;
  let myRegex: RegExp = /foo/;

  userName += 'Fabio';

  console.log(userName);

  const names: string[] = userName.split(' ');
  const myValues: Array<number> = [1, 2, 3]; //generic types

  console.log(names);
  console.log(myValues);

  interface Person {
    firstName: string;
    lastName: string;
  }

  const myPerson: Person = {
    firstName: 'Wicleice',
    lastName: 'Fabio',
  };

  console.log(myPerson.firstName);

  // Utility Type

  const ids: Record<number, string> = {
    10: 'a',
    20: 'b',
  };

  ids[30] = 'c';

  // loops

  myValues.forEach((v) => console.log(v));
  const out: number[] = myValues.map((v) => v * 10);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>hi</h1>
      </main>
    </div>
  );
};

export default Home;
